// Code generated by logcopter-gen; DO NOT EDIT.

package docmgr

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.gitcommit.cmd.gitcommit.cmds.docmgr")
