// Code generated by logcopter-gen; DO NOT EDIT.

package validate

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.gitcommit.pkg.validate")
